# Generated by Django 3.2.4 on 2021-06-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('course', models.CharField(max_length=250)),
                ('age', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=100)),
            ],
        ),
    ]
